# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nightNumber', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('ageRange', models.CharField(max_length=6)),
                ('sexPref', models.CharField(max_length=15)),
                ('mrtlStat', models.CharField(max_length=15)),
                ('mrtlLength', models.CharField(max_length=15)),
                ('theme', models.CharField(max_length=30)),
                ('foodEth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CoupleMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=100)),
                ('secondary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('episodeNumber', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69)], default=1)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppAVote', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0)),
                ('oppBVote', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0)),
                ('totalScore', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39)], default=0)),
                ('outcome', models.CharField(max_length=15)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='statApi.Couple')),
            ],
        ),
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='couplemeal',
            name='dessert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='statApi.Dessert'),
        ),
        migrations.AddField(
            model_name='couplemeal',
            name='entertainment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='statApi.Entertainment'),
        ),
        migrations.AddField(
            model_name='couplemeal',
            name='entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='statApi.Entree'),
        ),
        migrations.AddField(
            model_name='couplemeal',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='statApi.Starter'),
        ),
        migrations.AddField(
            model_name='couple',
            name='coupleMeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple', to='statApi.CoupleMeal'),
        ),
        migrations.AddField(
            model_name='couple',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple', to='statApi.Episode'),
        ),
    ]
